services:
  astream:
    image: dyhlio/astream:latest
    container_name: astream
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - ANIMESAMA_URL=https://example.com
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/data/astream.db
    restart: unless-stopped
