services:
  astream:
    image: dyhlio/astream:latest
    container_name: astream
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - astream:/data

volumes:
  astream:
